# Generated by Django 4.1.3 on 2022-12-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_user_avatar_alter_user_bio_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='social_accounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
